name: livro_receitas_mae
description: App offline-first de receitas da mãe

publish_to: 'none' # mantemos local por enquanto

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  uuid: ^4.4.0
  intl: ^0.19.0
  collection: ^1.18.0
  share_plus: ^10.0.2

  # Próximas sprints
  pdf: ^3.11.0
  printing: ^5.13.4
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.10
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.jpg
